Revisao
alura-cursos/HelloApp pull request #2
Opened 2022-10-21 16:13 UTC by git-jr

2022-10-21 18:09 UTC, alexfelipe requested changes
Deixei alguns comentários para realizar os ajustes, qualquer dúvida é só avisar

2022-10-21 18:09 UTC, alexfelipe commented on app/build.gradle
> +    def lifecycle_version = "2.6.0-alpha02"
evitar lib alpha

2022-10-21 18:09 UTC, alexfelipe commented on app/build.gradle
> +    // Room: https://developer.android.com/jetpack/androidx/releases/room
remover comentários

2022-10-21 18:09 UTC, alexfelipe commented on app/build.gradle
> +    annotationProcessor "androidx.room:room-compiler:$room_version"
pode usar o ksp

2022-10-21 18:09 UTC, alexfelipe commented on app/build.gradle
> +    kapt "androidx.room:room-compiler:$room_version"
pode remover a duplicidade

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/Extensions.kt
> +    return SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()).format(this)
pode extrair para uma constantes no próprio arquivo

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/data/Contato.kt
> +    val sobreNome: String = "",
veririfica se é `sobrenome` ao invés de `sobreNome`

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/data/Usuario.kt
> +    val usuario: String,
se achar um nome melhor pode colocar, por exemplo, `apelido`. (Opcional)

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +        fun getDatabase(context: Context): HelloAppDatabase {
Fazer o singleton

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/converter/Converters.kt
> +    fun dateParaLong(data: Date?): Long? {
adicionar o 'de' `deDateParaLong`

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +fun DataPickerDialogTest(
Remover o Test

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +    onDismiss: () -> Unit,
considerando o portugues, talvez faça sentido traduzir os eventos.

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +    val calendario = Calendar.getInstance()
Tente usar a `LocalDate`

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +fun DataPickerDialogTest(
Também utilizar em pt-br

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +        { _: DatePicker, ano: Int, mes: Int, dia: Int ->
quando tiver mais de 2 parâmetros, tente deixar em linhas separadas

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +    // Sem singleton por enquanto, mas adicionar antes de gravar
remover comentário

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +@Database(entities = [Contato::class], version = 1)
atenção ao gerador de schema.

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +                "heloApp.dp"
typo no nome do app

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +fun dataPickerDialog(
talvez traduzir o picker e dialog

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +        { _: DatePicker, _: Int, _: Int, _: Int ->
verificar se não há a necessidade de colocar o tipo

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +    val datePickerDialog = DatePickerDialog(
Quando tiver pra gravar o conteúdo, se achar a implementação apenas com o compose, seria o ideal

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +fun CarregaFotoDialog(
composables que apresentam conteúdo, devem ser substantivos ao invés de verbos

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +                    .heightIn(250.dp)
colocar o máximo `heightIn(250.dp, 300.dp)`

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +//                Button(
remover comentário

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +                    .fillMaxWidth()
adicionar heightIn com max

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/LifecycleComposable.kt
> +fun OnResumeCicloVidaAtual(
Remover esse composable e tentar usar as soluções reativas para atualizar automaticamente

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoActivity.kt
> +                    var contatoCarregado by remember { mutableStateOf(Contato()) }
usar o State Holder

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoActivity.kt
> +                    var contatoCarregado by remember { mutableStateOf(Contato()) }
Considere a implementação com o ViewModel

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoActivity.kt
> +        CadastroContent(
Acho que não precisa dessa extração, pode deixar no código da screen

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoActivity.kt
> +    val context = LocalContext.current
migrar para o state holder

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoActivity.kt
> +fun CadastroScreen(
extrair para um arquivo exclusivo

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +        val intent = intent
pode chamar direto

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +        val contatoDao = HelloAppDatabase.getDatabase(this).contatoDao()
manter o padrão e usar o lazy

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +                    OnResumeCicloVidaAtual(LocalLifecycleOwner.current) {
usar a reação a partir do flow

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +                        onBackClick = { finish() },
usar o navigation para navegar nas telas

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +                                Toast.makeText(
Verificar se tem um jeito compose de fazer

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +        DetalhesContatoContent(Modifier.padding(paddingValues), contato)
talvez considerar o slot

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +        Modifier.fillMaxSize(),
colocar o modifier padrão apenas no container

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +                    .clickable {},
remover clickable

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +                text = "4002-8922", style = MaterialTheme.typography.h6
remover o teste

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/DetalhesContatoActivity.kt
> +        1, "Ana", "Lura", "", "", Calendar.getInstance().time
talvez criar um sample

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/home/MainActivity.kt
> +        val database = HelloAppDatabase.getDatabase(this)
usar o viewmodel pra carregar o conte;udo na tela que precisa

2022-10-21 18:09 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/home/MainActivity.kt
> +private var contatosExemplo: List<Contato> = listOf(
jogar em um arquivo separado para samples

2022-10-24 12:38 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +    val calendario = Calendar.getInstance()
LocalDate limitaria essa parte do código ao Android 8+

2022-10-27 13:20 UTC, alexfelipe requested changes
tá ficando no esquema, precisa de mais algumas mudanças gg

2022-10-27 13:20 UTC, alexfelipe commented on app/build.gradle
>      implementation "io.coil-kt:coil-compose:2.2.2"
Adicionar o BOM do compose. Cada vez que gravar um conteúdo, lembre-se de usar as versões mais atualizadas

2022-10-27 13:20 UTC, alexfelipe commented on app/build.gradle
> +    kapt "androidx.room:room-compiler:$room_version"
talvez considerar o ksp

2022-10-27 13:20 UTC, alexfelipe commented on app/build.gradle
> +    implementation("androidx.navigation:navigation-compose:$nav_version")
usar apenas um padrão para declarar dependências, apenas string solta ou apenas com parenteses.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/DestinosHelloApp.kt
> +interface DestinosHelloApp {
avaliar se faz sentido a necessidade de uma interface para representar telas

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +        private var INSTANCIA: HelloAppDatabase? = null
verificar se a convenção para esse tipo de property está correto, ou seja, se é pra ficar em maiusculo ou minusculo

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +        private var INSTANCIA: HelloAppDatabase? = null
`Instance` -> https://kotlinlang.org/docs/coding-conventions.html#property-names

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/extensions/ContextExtensions.kt
> +        Toast.LENGTH_SHORT
considerar o uso como parâmetro para conseguir alterar entre short ou long. Pode assumir o short como valor padrão.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +    modifier: Modifier = Modifier,
colocar o modifier, após último parâmetro obrigatório

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +    context: Context
Ao invés de mandar o context, indica que ocorreu o evento que vc quer apresentar o Toast, e deixe a entidade que tem o context, fazer o toast, Activity/Fragment

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +        startDestination = ListaContatos.rota,
talvez considerar a criação de um objeto que representa a rota inicial lá no arquivo de rotas, cada vez que precisar mudar a rota inicial, muda apenas no arquivo de rotas.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                navBackStackEntry.arguments?.getLong(DetalhesContato.idContato, 0L)!!
não utilizar o `!!`, no momento que precisar do `idContato`, fazer o tratamento

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +            CadastroContatoTela(
testar se, o `idContato` receber um valor nulo e não apresentar a tela de cadastro se conta como uma task na back stack de navegação

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                viewModel = CadastroContatoViewModel(
É necessário usar o factory para vincular o ViewModel com a Activity https://developer.android.com/topic/libraries/architecture/viewmodel#implement-viewmodel

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                onClickApagar = {
Considerar a elevação do evento para que a Activity faça o que precisa ser feito e não seja necessário o envio do Context. A alternativa é utilizar o Local para pegar o Context.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +fun NavHostController.navegaParaCadastro(idContato: Long = 0L) {
talvez mudar o nome para formulário pq pode criar ou alterar

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/AsyncImagePerfil.kt
> +fun AsyncImagePerfil(modifier: Modifier, urlImagem: String) {
inverter parametros e deixar modifier opcional

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/components/Dialog.kt
> +    var urlImagem by remember { mutableStateOf(imageAtual) }
usar o state holder

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoTela.kt
> +fun DetalhesContatoTela(
Implementar a versão stateful e stateless

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoTela.kt
> +                    text = stringResource(R.string.informações),
não usar caracteres especiais

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoTela.kt
> +        title = { },
analisar sobrecargas do topAbbBar para não manter um slot vazio

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoUiState.kt
> +data class DetalhesContatoUiState(
colocar cada property que precisa ao invés do modelo inteiro

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +    val uiState: StateFlow<DetalhesContatoUiState> = _uiState.asStateFlow()
talvez considerar a convenção e usar o get() https://kotlinlang.org/docs/coding-conventions.html#names-for-backing-properties

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +            it?.let {
nomear o parametro dentro do let, por exemplo, `contato`.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +    fun removeCotato() {
Cotato -> Contato

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoTela.kt
> +fun CadastroContatoTela(
criar versão stateful e stateless

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoTela.kt
> +        val context = LocalContext.current
remvoer o context pq não é necessário na tela

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoTela.kt
> +                            Contato(
não precisa enviar o objeto, pq o viewmodel tem o ui state que tem todos os dados que precisa para criar o objeto necessário

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoUiState.kt
> +    val contato: Contato = Contato(),
colocar campos separadamente

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoViewModel.kt
> +    fun salvarContato(contato: Contato) {
o ui state tem o contato, não precisa recebê-lo.

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/CadastroContatoViewModel.kt
> +    fun defineTextoAniversario(stringResource: String): String {
mudar o nome para ser o texto do aniversário

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/home/ListaContatosTela.kt
> +                    onClickAbreDetalhes(contato)
pode mandar apenas o id

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/util/AuxilarRecursoString.kt
> +sealed class AuxilarRecursoString {
remover

2022-10-27 13:20 UTC, alexfelipe commented on app/src/main/res/values/strings.xml
>      <string name="title_activity_cadastro_contato">Adicionar contato</string>
manter apenas em pt-br ou apenas em ingles

2022-10-29 19:09 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +        private var INSTANCIA: HelloAppDatabase? = null
Segundo a orientação da doc do Kotlin, singletons podem ser nomeados das duas formas, tanto PascalCase como com tudo em maiúsculo, resolvei mudar para "Instancia"

2022-10-29 19:10 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +            CadastroContatoTela(
Resultado do teste: Conta sim a task na back stack, a tela fica vazia, mas o botão de voltar leva de volta a tela / destino anterior normalmente.

2022-10-29 19:11 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoTela.kt
> +        title = { },
Testei e a a sobrecarga sem o "title" também não contém "actions" e "navigationIcon" necessários nessa implementação, estranho.

2022-10-31 13:52 UTC, alexfelipe requested changes
Falta só pequenos ajustes

2022-10-31 13:52 UTC, alexfelipe commented on app/build.gradle
> +        kotlinCompilerExtensionVersion = "1.3.0"
acho que a versão atual é a 1.3.2. Dá sempre pra acompanhar nessa página https://developer.android.com/jetpack/androidx/releases/compose#versions

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/DestinosHelloApp.kt
> +    const val rota = "lista_contatos"
Nesse caso, utilize a property `rota` de um dos objetos, nesse caso da `ListaContatos`.

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/HelloAppAplication.kt
> +    val database: HelloAppDatabase
Há um motivo para chamar a instância direto no Application? A intenção é 'garantir' que vai ser um singleton?

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/HelloAppViewModelFactory.kt
> +fun helloAppViewModelFactory(idContato: Long): ViewModelProvider.Factory {
Assim como conversamos, simplificar a implementação para facilitar a explicação do conteúdo

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/database/HelloAppDatabase.kt
> +                    "helloApp.dp"
acho que aqui seria '.db'

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                onClickDesloga = {},
Se não usa ou não implementa ou remove.

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                    onClickVoltar = { navController.navigateUp() },
pode considerar o pop ao invés do navigateUp.

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +        viewModelScope.launch {
vai mudar o init pq vai carregar pelo método

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +    fun removeContato() {
considerar como suspend para não do launch interno

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoTela.kt
> +    viewModel: DetalhesContatoViewlModel = viewModel(),
Remover essa criação pq apresenta bug quando vc não envia o viewmodel na navegação

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/FormularioContatoTela.kt
> +            viewModel.mostraCaixaImagem()
pode fazer a implementação desses eventos direto no ViewModel, pois alteram um valor interno do ui State. Após essa migração, o Stateless não precisa mais elevar os eventos.

2022-10-31 13:52 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/form/FormularioContatoViewModel.kt
> +    fun defineTextoAniversario(textoAniversario: String): String {
Evitar essa implementação e atualizar apenas no ui state

2022-10-31 13:52 UTC, alexfelipe commented on build.gradle
> -        compose_ui_version = '1.2.1'
ao utilizar o bom, não precisa mais manter variável com a versão do compose, pode remover

2022-11-01 13:15 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/HelloAppAplication.kt
> +    val database: HelloAppDatabase
Coma a simplificação dos viewmodels achei melhor nem utilizar essa classe a removi

2022-11-17 16:48 UTC, closed without merging