Hilt test - Review
alura-cursos/HelloApp pull request #4
Opened 2022-11-14 14:44 UTC by git-jr

- Adição do Hilt para injeção de dependências
> Injeção de de DAO nos Viewmodels

- Remoção dos factorys de cada ViewModel
> Agora os parâmetros são passados aos ViewModels com savedStateHandle e auxílio de arguments do Navigation

- Troca do padrão stateful - stateless
> De volta ao padrão antigo com alguns refinamentos

2022-11-14 15:46 UTC, alexfelipe requested changes
O código ficou topzera, ein! Imagino que faltam pequenos detalhes, parabéns! 👏

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/HelloAppViewModelFactory.kt
> +                        // TODO:
é importante remover qualquer comentário

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +            val dataStore = LocalContext.current.dataStore
Composable não deve lidar com regra de negócio que envolve qualquer referência da camada de dados. Dao, webclient ou qualquer outro data source (como o data store), devem ser acessados apenas pelo ViewModel.

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                viewModel.defineTextoAniversario(
Se essa chamada modifica estado, ela vai ser executada N considerando que está sujeita a recomposição. Existe alguma restrição para ela não ser feita internamente no VM?

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/DestinosHelloApp.kt
>  object DestinoInicial {
Tudo bem manter dessa forma, porém, é válido lembrar que daria pra resolver com o type safety e evitaria essa abordagem

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                    onClickVoltar = { navController.navigateUp() },
há motivo para usar o navigateUp()? Caso não, mantenha o popBackStack

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +    savedStateHandle: SavedStateHandle
Show, usou o savedStateHandle. Eu ainda não fiz uma intro de como usa isso na prática, só com atividades para saber mais. Se for o caso, a gente pode criar um material extra

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +                    _uiState.value = _uiState.value.copy(
uma coisa que eu estava avaliando sobre ui state, vamos supor que a gente comece a ter um modelo cada vez maior... Fica muito ruim de escrever o código para cada campo, ou seja, talvez faça sentido criar um modelo dentro do ui state, por exemplo:

```kotlin
class DetalhesContatoUiState {
     data class Contato(
         val nome: String,
         ...
     )
}
```

A parte 'chata' é que vamos fazer 2 copies, 1 para o ui state e outro para o objeto mais interno... Por enquanto é uma ideia, mas pode ser algo que faça sentido avaliarmos

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/login/FormularioLoginViewModel.kt
> +class FormularioLoginViewModel : ViewModel() {
Mesmo que não tenha as dependências, pode colocar com a anotação do hilt. Curioso que funcionou com o navigation, né? Teoricamente, não era para funcionar se fez a injeção com o Hilt.

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/login/LoginViewModel.kt
> +class LoginViewModel : ViewModel() {
mesma coisa do hilt aqui

2022-11-14 15:46 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
>              navBackStackEntry.arguments?.getLong(
isso é o suficiente para ficar acessível no savedInstanceHandle?

2022-11-14 16:23 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/HelloAppViewModelFactory.kt
> +                        // TODO:
Ok, na verdade esse arquivo todo não precisa existir mais, vou removê-lo.

2022-11-14 16:26 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                viewModel.defineTextoAniversario(
Aqui é aquele caso de antes, onde eu preciso acessar "stringResource" ou "getString" então não é possível fazer no viewModel sem um Context

2022-11-14 16:34 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +                    _uiState.value = _uiState.value.copy(
Acho que faz muito sentido se os ui state começarem a fica muito grandes, por agora vou manter a abordagem anterior mesmo.

2022-11-14 16:37 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/login/FormularioLoginViewModel.kt
> +class FormularioLoginViewModel : ViewModel() {
Funcionou, mas pode ser porque esse VM não lida com nenhum dao

2022-11-14 16:42 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
>              navBackStackEntry.arguments?.getLong(
Estranhamente sim, é o suficiente. Fiz alguns testes pra ver se mudando o nome dos pareamentos parava de funcionar e para.

2022-11-14 16:52 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +                    onClickVoltar = { navController.navigateUp() },
Nenhum motivo específico, fiz a troca por popBackStack e mantém o mesmo comportamento

2022-11-14 16:53 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/details/DetalhesContatoViewlModel.kt
> +    savedStateHandle: SavedStateHandle
blz

2022-11-14 16:56 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> +            val dataStore = LocalContext.current.dataStore
verdade, vou mover as referências de DataStore para o viewModel

2022-11-16 17:00 UTC, alexfelipe requested changes
Só mais alguns detalhes, tá quase lá o/

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/navigation/FormularioContatoNavigation.kt
> +            viewModel.defineTextoAniversario(
A cada recomposição esse código será chamado novamente, o ideal é usar alguma API para chamar apenas quando precisar, imagino que seja apenas uma vez, certo? Se for o caso, algo como um LaunchEffect seja o suficiente. Outro ponto, essa definição é feita dado que exista um id do contato, é isso? Se for esse o caso, você pode aplicar a regra no momento que o id for alterado no viewmodel.

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> -    this.popBackStack(Login.rota, true)
se é extension, não precisa do `this`

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/home/ListaContatosActivity.kt
> +    lateinit var splashScreenViewModel: SplashScreenViewModel
se é viewmodel, pode usar a delegation by que é integrado com o hilt

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/home/ListaContatosActivity.kt
> +                    splashScreenViewModel.uiState.collectAsState().value.destino_inicial
geralmente não modificamos destino inicial, por isso parece estranho ser um state, geralmente é algo fixo. Teve um motivo para fazer diferente?

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/login/LoginViewModel.kt
> +    suspend fun logar() {
O logar parece que tá fazendo mais coisas do que deveria, pois ele está observando a mudança do DataStore e ao mesmo tempo faz uma edição. É um típico comportamento de um listener global... Dado o nome e intenção do método, o ideal é que ele apenas pegasse a informação atual e ajustasse o que precisasse.

2022-11-16 17:00 UTC, alexfelipe commented on app/src/main/java/br/com/alura/helloapp/ui/splashscreen/SplashScreenUiState.kt
> +    val destino_inicial: String = DestinoInicial.rota
nomeação fora do padrão

2022-11-16 17:21 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/HelloAppNavHost.kt
> -    this.popBackStack(Login.rota, true)
Ok, todos this removidos

2022-11-16 17:23 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/home/ListaContatosActivity.kt
> +    lateinit var splashScreenViewModel: SplashScreenViewModel
delegation aplicado

2022-11-16 17:30 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/navigation/FormularioContatoNavigation.kt
> +            viewModel.defineTextoAniversario(
"LaunchedEffect(Unit)" aplicado para resolver o problema da recomposição. 

Sobre aplicar a regra dentro do viewModel, sim ele é feita caso um id exista, mas a aplicação dela só pode ocorrer em um lugar que seja capaz de acessar "getString" ou "stringResource"

2022-11-16 17:50 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/home/ListaContatosActivity.kt
> +                    splashScreenViewModel.uiState.collectAsState().value.destino_inicial
O destino inicial muda apenas uma única vez na inicialização do app, que é quando a splashscreen verifica se o fluxo do app vai para login ou não.

Eu havia feito uma implementação parecida com essa, depois pesquisei e vi que que outras pessoas também fizeram assim, aí mantive.
Mesmo assim, esse trechinho de código foi um dos que mais fiquei com o pé atrás em todo projeto kkkk

2022-11-16 17:51 UTC, git-jr commented on app/src/main/java/br/com/alura/helloapp/ui/login/LoginViewModel.kt
> +    suspend fun logar() {
Beleza, mudei algumas coisas aqui então:
- Primeiro, o nome "tentaLogar" acho que faz mais sentido do que "logar" nesse caso.
Criei um método adicional, que faz a edição tanto no state quanto no datastore.

2022-11-17 16:50 UTC, merged